# Generated by Django 4.0.3 on 2022-04-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
