# Generated by Django 4.0.3 on 2022-04-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendApp', '0004_contacto_staff_ventas_rename_productos_tiendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='telefono',
        ),
    ]
