# Generated by Django 4.0.3 on 2022-04-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendApp', '0005_remove_tiendas_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
