# Generated by Django 4.0.3 on 2022-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendApp', '0006_remove_contacto_id_alter_contacto_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
