# Generated by Django 4.0.3 on 2022-04-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendApp', '0007_remove_staff_id_alter_staff_dni_alter_ventas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='puesto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
