# Generated by Django 4.0.3 on 2022-04-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendApp', '0009_alter_ventas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='stock',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
